### ISSUE TITLE
(OP-Req-max_age=10000) Not one authentication

### ISSUE THREAD

**Issue by lroman2025** [openid-certification/oidctest#83] opened 2018-03-21 13:53 UTC
I have problem with passing this test: first auth request is made without max_age parameter and so is id token generated, after this next auth request is made with max_age=10000 and it generated new idToken, becouse we need to update "exp" parameter in idToken. Why test assume that two idTokens need to be same?

**Comment by panva** [comment] 2018-03-22 12:18
It doesn't assume the id token will be the same. Can you provide the log output?

**Comment by selfissued** [comment] 2018-05-31 16:30
Given that no additional information has been provided, we are closing this with no action.

**Comment by hiruandon** [comment] 2018-12-06 08:07
I also experienced the same situation. The test fails.
(The test of OP-Req-max_age = 1 has been successful.)

Logs and execution results can be confirmed with the following instances.
https://op.certification.openid.net:60595/

What is SameAuthn testing for?

**Comment by zandbelt** [comment] 2018-12-06 08:33
the test verifies that the `auth_time` claim in the `id_token` is set to the same value in both authorization responses; I believe that could be spelled out more clearly in the test description, hence I'm re-opening; let us know if that helps

**Comment by hiruandon** [comment] 2018-12-06 09:19
Re-opening Thank you.

I will check the specifications of auth_time and max_age from now.

I will report when the problem is resolved.

**Comment by hiruandon** [comment] 2018-12-07 03:33
Hi.

> the test verifies that the auth_time claim in the id_token is set to the same value in both authorization responses

I understand.
We modified to return the same value. The test was successful.
I think the explanation of the test and the result message are accurate.

The problem has been solved, please close it.

Thank you very much.

**Closed** 2019-07-25 09:29 UTC
