### ISSUE TITLE
Software Statement and Initial Access Token for dynamic client registration

### ISSUE THREAD

**Issue by Spomky** [openid-certification/oidctest#72] opened 2017-11-29 14:16 UTC
Hi,

Is it possible to add the support for the optional [Software Statement and the Initial Access Token](https://tools.ietf.org/html/rfc7591#section-1.3) request parameters to that validation tool?

Thanks.

**Comment by zandbelt** [comment] 2017-11-29 16:29
Note that the spec referred to is about OAuth 2.0 Dynamic Client Registration whereas this suite is about OpenID Connect and as such OpenID Connect's Dynamic Client Registration that predates the former. The latter spec doesn't explicitly mention the software statement (so I'd say that's more likely to be out of scope) but does mention the initial access token mechanism: http://openid.net/specs/openid-connect-registration-1_0.html#ClientRegistration

**Comment by travisspencer** [comment] 2017-11-29 17:20
This is actually two requests:

1. Support for `software_statement` and
2. Support for initial access token

2 seems to be a duplicate of #59 . `software_statement` is closely related to `software_id` requested (by me) in #60. 

I think that support for initial access tokens, `software_statement` and `software_id` are very useful when testing an OIDC Provider that supports DCR.  

While I understand your point, @zandbelt, that this suite is for testing OPs, most support vanilla OAuth as well. Furthermore, many OP implementation allow/require an initial access token, `software_id` and/or `software_statement` to register a dynamic client. (We had to add support for unauthenticated DCR just to pass these tests; no customers really use that.) This doesn't make those OPs that use these inputs incompatible with OIDC, just beyond the scope of the (current) spec version.

**Comment by selfissued** [comment] 2018-01-10 17:43
Closing because this is a duplicate of #59 and #60 .

**Closed by selfissued** 2018-01-10 17:43 UTC
Labels: enhancement
